### ISSUE TITLE
LinesChartModel setRangeMin is not rendered

### ISSUE THREAD

**Issue by simonsymhoven** [uhafner/echarts-build-trends#206]
I set up the following LinesChartModel:

```
public LinesChartModel create(final Iterable<? extends BuildResult<ReportBuildAction>> results,
                                  final ChartModelConfiguration configuration, String id) {

        AssetSeriesBuilder builder = new AssetSeriesBuilder(id);
        LinesDataSet dataSet = builder.createDataSet(configuration, results);

        LinesChartModel model = new LinesChartModel(dataSet);
        
        if (!dataSet.isEmpty()) {
            model.useContinuousRangeAxis();

            model.setRangeMax(Math.max(
                    Math.max(createRangeMaxFor(dataSet, ReportSeriesBuilder.ACCURATE),
                            createRangeMaxFor(dataSet, ReportSeriesBuilder.MANUALLY)),
                    createRangeMaxFor(dataSet, ReportSeriesBuilder.INCORRECT)) + 10);

            // we always start from the zero line
            model.setRangeMin(0);

            LineSeries accurateSeries = new LineSeries("Accurate", Palette.GREEN.getNormal(),
                    LineSeries.StackedMode.STACKED, LineSeries.FilledMode.FILLED);
            accurateSeries.addAll(dataSet.getSeries(AssetSeriesBuilder.ACCURATE));
            model.addSeries(accurateSeries);

            LineSeries manuallySeries = new LineSeries("Manually", Palette.YELLOW.getNormal(),
                    LineSeries.StackedMode.STACKED, LineSeries.FilledMode.FILLED);
            manuallySeries.addAll(dataSet.getSeries(AssetSeriesBuilder.MANUALLY));
            model.addSeries(manuallySeries);

            LineSeries incorrectSeries = new LineSeries("Incorrect", Palette.RED.getNormal(),
                    LineSeries.StackedMode.STACKED, LineSeries.FilledMode.FILLED);
            incorrectSeries.addAll(dataSet.getSeries(AssetSeriesBuilder.INCORRECT));
            model.addSeries(incorrectSeries);
        }
        return model;
    }
```

but the y-axis ignores the `model.setRangeMin(0)`.

<img width="580" alt="Bildschirmfoto 2022-06-07 um 13 54 28" src="https://user-images.githubusercontent.com/26878018/172372974-dee52324-2db1-4e32-a5a3-0c0f9aba18fa.png">

The generated model:

`{
   "domainAxisLabels":[
      "#1",
      "#2",
      "#3",
      "#4"
   ],
   "buildNumbers":[
      1,
      2,
      3,
      4
   ],
   "series":[
      {
         "name":"Accurate",
         "type":"line",
         "symbol":"circle",
         "data":[
            30,
            20,
            20,
            20
         ],
         "itemStyle":{
            "color":"#A5D6A7"
         },
         "areaStyle":{
            "normal":true
         },
         "stack":"stacked"
      },
      {
         "name":"Manually",
         "type":"line",
         "symbol":"circle",
         "data":[
            2,
            7,
            7,
            7
         ],
         "itemStyle":{
            "color":"#FFF59D"
         },
         "areaStyle":{
            "normal":true
         },
         "stack":"stacked"
      },
      {
         "name":"Incorrect",
         "type":"line",
         "symbol":"circle",
         "data":[
            1,
            6,
            6,
            6
         ],
         "itemStyle":{
            "color":"#EF9A9A"
         },
         "areaStyle":{
            "normal":true
         },
         "stack":"stacked"
      }
   ],
   "domainAxisItemName":"Build",
   "integerRangeAxis":false,
   "rangeMax":40,
   "rangeMin":0
}`

Does this behave as expected or why does the y-axis not start at 0? Thanks in advance!

**Comment by uhafner** [comment]
Fixed by https://github.com/jenkinsci/echarts-api-plugin/pull/236
