### ISSUE TITLE
Move chart model from integer to float

### ISSUE THREAD

**Issue by uhafner** [uhafner/echarts-build-trends#212]
Currently, all charts are using integers for the values in the range and domain axes. It would make sense to allow float values for the domain axis as well.

See https://github.com/jenkinsci/code-coverage-api-plugin/issues/424#issuecomment-1194988130

**Comment by mdealer** [comment]
Coming from the JUnit plugin, there is also no way to have a multicolored series and marked ares like [here](https://echarts.apache.org/examples/en/editor.html?c=line-sections), which was basically what the old chart was doing. I am no longer sure that moving JUnit to ECharts was a good idea.

**Comment by uhafner** [comment]
Can you please describe more precisely what is missing and where? I think the best thing would be a new feature request (here or in the corresponding Jenkins plugin).
