### ISSUE TITLE
Unnecessarily large dependency

### ISSUE THREAD

**Issue by daniel-beck** [uhafner/echarts-build-trends#225]
https://github.com/uhafner/echarts-build-trends/blob/0b90f72fe2a5ac831842f60e7683e868b5f27bcb/src/main/java/edu/hm/hafner/echarts/SeriesBuilder.java#L11-L13

It looks like the dependency supporting these imports contributes to 11MB of the `echarts-api` plugin size, wasting bandwidth (and time when installing). That seems excessive, especially given that, at a glance, the use could easily be replaced by basic JDK types.

**Comment by uhafner** [comment]
How? JDK 8 has no multi maps.

**Comment by daniel-beck** [comment]
> JDK 8 has no multi maps.

Multimaps are just maps of lists, though? I submitted #226 for your consideration.
